[default]
mongo_uri = 'mongodb://localhost:27017/blog'
title = 'Meu Blog'
extensions = [
    "blog.database:init_app",
    "blog.commands:init_app",
    "flask_bootstrap:Bootstrap",
    "blog.views:init_app",
    "blog.plugins:init_app",
]